server:
  port: 8086
spring:
  application:
    name: user-service   # Name of the microservice
  datasource:
    url: jdbc:mysql://localhost:3306/akhil
    username: root
    password: flgmp
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update   # Or validate / create / none / create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
    instance:
        prefer-ip-address: true
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG

